app.branch-name= Nha Thuoc So 1
app.hotline=19000000
pharmacy.vat-rate=0.05

spring.datasource.url=jdbc:postgresql://localhost:5434/pharmacy_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=19052004
